name: Auto-Update Docs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Install Dependencies
        run: |
          pip install build sphinx sphinx_rtd_theme
      - name: Clone the main repo
        run: |
          git clone https://github.com/pdpy-org/pdpy.git
      - name: Install local pdpy and make the docs
        run: |
          cd pdpy && make local && make doc
      - name: Copy documentation changes and remove pdpy
        run: |
          cp -r pdpy/docs/_build/html/* .
          rm -rf pdpy/
      - name: Commit documentation changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-Update documentation"
          git push